server:
  port: 8080

auth:
  server: https://sagar-pc:7777/auth/login

access:
  permission: miv-access



spring:
  boot:
    admin:
      client:
        url: https://sagar-pc:9090
  zipkin:
      enabled: true
      base-url: https://sagar-pc:9411
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: customerModule
          uri: lb://miv-customer-service
          predicates:
            - Path=/api/customer/**
        - id: accountModule
          uri: lb://miv-account-service
          predicates:
            - Path=/api/account/**


eureka:
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://sagar-pc:8761/eureka/
      default-zone: https://sagar-pc:8761/eureka/
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://sagar-pc:${server.port}/actuator/info
    healthCheckUrl: https://sagar-pc:${server.port}/actuator/health
    homePageUrl: https://sagar-pc:${server.port}/ 